global.nameOwner = `By Waen`
global.nameBot = `Kurumi Tokisaki`
global.nomorOwner = `6283173416973`
global.nomorBot = `6282184407525`
global.groupWa = `https://chat.whatsapp.com/EFe20NTS2vrDs3K5cvdApt`
global.saluranWa = `https://whatsapp.com/channel/0029VacKjEwKbYMUyCLyCj0O`
global.info = `https://heylink.me/ByWaen`
global.donasi = `https://saweria.co/ByWaen`
global.thumb = `https://telegra.ph/file/12a6c7659c4892f5333ee.jpg`
global.wm = `© Waen`
global.wm1 = `Created By Waen`
global.wait = `_*Tunggu sedang di proses...*_`
global.error = `*Fitur lagi error!!*`